name: varnja_church
description: Church website
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  country_flags: ^2.2.0
  dio: ^5.4.0
  envied: ^0.5.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_native_splash: ^2.3.6
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.18.1
  logging: ^1.2.0
  pubspec_dependency_sorter: ^1.0.4
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2
  envied_generator: ^0.5.2

flutter:
  assets:
    - assets/launcher_icon.png
    - assets/web_icon/launcher_icon.png
    - assets/website_assets/church_main.jpg
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true